### ISSUE TITLE
Inconsistency in tutorial explaining the forge.

### ISSUE THREAD

**Issue by raulcd** [puppetlabs/puppetlabs-training-bootstrap#390]
On the line https://github.com/puppetlabs/puppetlabs-training-bootstrap/blob/master/modules/learning/files/lvmguide/files/html/quests/puppet_module_tool_quest.html#L255 it says that you can check the init.pp:

```
cd /etc/puppetlabs/puppet/modules/mysql/manifests   
nano init.pp
```

There are two issues here. 

Previously in the tutorial (https://github.com/puppetlabs/puppetlabs-training-bootstrap/blob/master/modules/learning/files/lvmguide/files/html/quests/puppet_module_tool_quest.html#L248) it explains you to remove the mysql module, so people will remove it, therefore the folder  ```/etc/puppetlabs/puppet/modules/mysql``` doesn't exist anymore. I think we should move the removal of the package to a later stage on the tutorial so the user can check the mysql module files:

```
puppet module uninstall puppetlabs-mysql
```

But if you install the module you can also check that the file ```init.pp``` doesn't exist:
```
[root@learning /etc/puppetlabs/puppet/modules/mysql/manifests]# ls
bindings  bindings.pp  client  client.pp  db.pp  params.pp  server  server.pp
[root@learning /etc/puppetlabs/puppet/modules/mysql/manifests]# 
```

**Comment by casharma** [comment]
This has been fixed with the refresh of the materials and the new Learning VM. Please refer to https://github.com/puppetlabs/courseware-lvm for quest content etc.
